# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48672bd920bc4a995dfa011f12101cd677d3fa5187d48d5e7d0301bc109214ebb6c7d1197209bad4069215d9b46d2f5371071088583989cdea48fc30609ca387

test:
  secret_key_base: 7aea6497f49638df21365135b9eb56b0837f3308c7979e444cabeb9721295c6adbf4f3eb5a6e7fcaee2b7a77f1e3e769e66a4bf7cf75ec5184ffc36614f36ee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
